import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "../_components/Navbar";
import { api } from "@/trpc/server";
import { auth0 } from "@/lib/auth0";
import { redirect } from "next/navigation";
import Footer from "../_components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Fetch the user session
  const session = await auth0.getSession();
  const user = session?.user;
  
  let loggedIn = false;
  if (user) {
    loggedIn = true;  
  }

  return (
    <html lang="en" className={GeistSans.variable}>
      <body>
        <Navbar loggedId={loggedIn} />
        {children}
      <Footer/>
      </body>
    </html>
  );
}
